Beacon
AlbertaSat/ex2_athena_software pull request #18
Opened 2021-11-19 19:51 UTC by yunqingyi

Format with clang, edit headers, delete delay, add macro for # of temp sensors on athena, resolve conflicts with a different branch.

2021-11-20 19:53 UTC, nsorense4 requested changes

2021-11-20 19:53 UTC, nsorense4 commented on equipment_handler/source/housekeeping_athena.c
> +    athena_hk->OBC_software_ver = csp_ntoh8(athena_hk->OBC_software_ver);
A version function will need to be added - useful for testing. @Taylorr82 had some ideas about git versioning.

2021-11-20 19:53 UTC, nsorense4 commented on equipment_handler/source/housekeeping_athena.c
> +    // Unit will be deca-seconds due to size restraint, seconds = OBC_uptime*10
wouldnt it be better to store it in minutes then?

2021-11-26 19:20 UTC, Taylorr82 commented on equipment_handler/source/tempsense_athena.c
> +uint8_t tmp_addr[NUM_TEMP_SENSOR] = {0x49, 0x4A};
These numbers should also be macros

2021-11-26 19:28 UTC, Taylorr82 approved these changes

2021-11-26 19:28 UTC, merged